# Generated by Django 5.0.4 on 2024-04-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
